ex06javdb8Com/bt-master/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search', views.SearchView.as_view(), name='search'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('commit', views.CommitView.as_view(), name='commit'),
    path('demo', views.DemoView.as_view(), name='demo'),
]

ex06javdb8Com/bt-master/bt/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', views.IndexView.as_view(), name='home'), # 默认首页
]

ex06javdb8Com/bt-master/app/models.py
from django.db import models

# Create your models here.
from django.db.models import Q


class LinkQuerySet(models.query.QuerySet):

    def get_search_list(self, q):
        if q:
            return self.filter(status=True).filter(Q(title__contains=q)).order_by('-timestamp')
        else:
            return self.filter(status=True).order_by('-timestamp')

    def get_recommend_list(self):
        return self.filter(status=True).order_by('-hot')[:4]

    def get_fake_list(self):
        return self.filter(status=True).order_by('-hot')[:]

class Link(models.Model):
    list_display = ("url","desc","contact")
    url = models.CharField(max_length=100,blank=True, null=True)
    title = models.CharField(max_length=100,blank=True, null=True)
    size = models.CharField(max_length=100,blank=True, null=True)
    hot = models.IntegerField(default=0)
    desc = models.CharField(max_length=200,blank=True, null=True)
    contact = models.CharField(max_length=100,blank=True, null=True)
    status = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    objects = LinkQuerySet.as_manager()

    def __str__(self):
        return self.title

    class Meta:
        db_table = "bt_link"

    def increase_hot_count(self):
        self.hot += 1
        self.save(update_fields=['hot'])

ex06javdb8Com/bt-master/app/forms.py
from django import forms

from app.models import Link


class CommitForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['url','title','size','desc', 'contact']

ex06javdb8Com/bt-master/app/views.py
import time

from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from ratelimit.decorators import ratelimit

from app.forms import CommitForm
from app.models import Link
from helpers import get_page_list


class IndexView(generic.TemplateView):
    template_name = 'app/index.html'

class SearchView(generic.ListView):
    model = Link
    template_name = 'app/search.html'
    context_object_name = 'link_list'
    paginate_by = 10
    q = ''       # 搜索词
    duration = 0 # 耗时
    record_count = 0

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        context['q'] = self.q
        context['duration'] = round(self.duration,6)
        context['record_count'] = self.record_count
        return context

    def get_queryset(self):
        start = time.time()
        self.q = self.request.GET.get("q", "")
        search_list = Link.objects.get_search_list(self.q)
        # 如搜索为空，则放假数据
        if len(search_list) <= 0:
            search_list = Link.objects.get_fake_list()
        end = time.time()
        self.duration = end - start
        self.record_count = len(search_list)
        return search_list

class DetailView(generic.DetailView):
    model = Link
    template_name = 'app/detail.html'

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.increase_hot_count()
        return obj

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        recommend_list = Link.objects.get_recommend_list()
        context['recommend_list'] = recommend_list
        return context

class CommitView(generic.CreateView):

    model = Link
    form_class = CommitForm
    template_name = 'app/commit.html'

    @ratelimit(key='ip', rate='2/m')
    def post(self, request, *args, **kwargs):
        was_limited = getattr(request, 'limited', False)
        if was_limited:
            messages.warning(self.request, "操作太频繁了，请1分钟后再试")
            return render(request, 'app/commit.html', {'form': CommitForm()})
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "提交成功! 审核期3个工作日。")
        return reverse('app:commit')

class DemoView(generic.TemplateView):
    template_name = 'app/demo.html'

ex06javdb8Com/bt-master/templates/app/commit.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div id="wrapper">
    <div class="top-bar">
        <span class="first">
          <span class="highlight-bar"></span>
          <a href="/" class="selected">首页</a></span>
        <span class="top_fav">
          <a href="" target="_blank">提交链接</a></span>
    </div>
    <div id="first-content">
        <div id="center-box-wrapper">
            <form  action="{% url 'app:commit' %}" enctype="multipart/form-data" method="post" role="form" style="width:50%;max-width:480px; min-width:320px;margin:auto auto;">
                {% csrf_token %}
                <div class="form-group">
                    <h3>请提交合法的磁力链接</h3>
                    <input style="margin:20px 0px;" required name="url" type="text" class="form-control" placeholder="磁力链接，例如：magnet:?xt=urn:btih:cbe569604ea7759b4167">
                    <input style="margin:20px 0px;" required name="title" type="text" class="form-control" placeholder="影片名称，例如：泰坦尼克号">
                    <input style="margin:20px 0px;" required name="size" type="text" class="form-control" placeholder="影片大小，例如：1.2Gb">
                    <input style="margin:20px 0px;" name="contact" type="text" class="form-control" placeholder="联系方式，例如：net123@163.com">
                    <textarea name="desc" required style="margin:20px 0px;" class="form-control" rows="3" placeholder="请输入简介，例如：《泰坦尼克号》是一部于1997年上映的美国史诗浪漫灾难电影，电影部分情节是根据1912年4月的泰坦尼克号沉没事故改编。"></textarea>
                    <button class="btn btn-primary" type="submit">提交</button>
                </div>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}
            </form>
        </div>
    </div>
    <div class="push"></div>
</div>

{% endblock content %}

ex06javdb8Com/bt-master/templates/app/demo.html
{% load static %}

<!doctype html>

<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>WebcamJS Test Page</title>
    <script src="{% static 'js/webcam.min.js' %}"></script>
</head>

<body>

	<div id="my_camera"></div>
	<input type=button value="截取" onClick="take_snapshot()">
	<input type=button value="连续截取" onClick="multi_snapshot(5)">
	<div id="results"></div>

	<!-- Code to handle taking the snapshot and displaying it locally -->
	<script language="JavaScript">
		Webcam.set({
			width: 320,
			height: 240,
			image_format: 'jpeg',
			jpeg_quality: 90
		});
		Webcam.attach('#my_camera');
		function take_snapshot() {
			// take snapshot and get image data
			Webcam.snap(function (data_uri) {
				// display results in page
				document.getElementById('results').innerHTML = document.getElementById('results').innerHTML +
					'<div><img style="display:block; width:320px; height: 240px" src="' + data_uri + '"/></div>';
			});
		}
		function multi_snapshot(count) {
			for (var i = 0; i < count; i++) {
				setTimeout(function () { take_snapshot() }, 1000 * (i + 1))
			}
		}
	</script>

</body>

</html>

ex06javdb8Com/bt-master/templates/app/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div id="wrapper">
    <div class="top-bar">
        <span class="first"><a href="/">首页</a></span><span class="top_fav">
        <a href="{% url 'app:commit' %}" target="_blank">提交链接</a></span>
    </div>
    <div class="header-div">
        <form class="search-form"   action="{% url 'app:search' %}" enctype="multipart/form-data" method="get" role="form">
            <a href="/" title="磁力搜索" class="fl">
                <img src="{% static 'img/logo.png' %}" alt="磁力搜索" class="nav-logo"></a>
            <input type="text" id="search" title="Search" value="{{q}}"
                   autocomplete="off" name="q" placeholder="搜搜你懂的" class="fl mt25">
            <input style="line-height:32px;" type="submit" id="btnSearch" value="搜 索" class=" blue fl mt25">
        </form>
    </div>
    <div id="content">
        <div id="wall">
            <h1 class="res-title">{{link.title}}</h1>
            <div class="fileDetail">
                <p>
                    {% for item in recommend_list %}
                    <a href="{% url 'app:search' %}?q={{item.title}}" target="" class="pill">{{item.title}}</a>
                    {% empty %}
                    <h3>暂无推荐</h3>
                    {% endfor %}
                </p>
                <p>
                    视频大小：{{link.size}}
                </p>
                <p>
                    收录时间：{{link.timestamp}}
                </p>
                <p>
                    点击热度：<span id="hits_num">{{link.hot}}</span>
                </p>
                <p>
                    资源下载：<a href="{{link.url}}" class="download"
                            id="down-link">磁力链接</a>&nbsp;
                    <input id="mg-link" value="{{link.url}}">
                    <a href="javascript:;" id="copyi" data-clipboard-target="#mg-link" class="download">复制链接</a>&nbsp;
                </p>
                <p>
                    视频简介：
                </p>
            </div>
            <ol>
                {{link.desc}}
            </ol>
            <div class="push">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ex06javdb8Com/bt-master/templates/app/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div id="wrapper">
    <div class="top-bar">
        <span class="first">
          <span class="highlight-bar"></span>
          <a href="/" class="selected">首页</a></span>
        <span class="top_fav">
          <a href="{% url 'app:commit' %}" target="_blank">提交链接</a></span>
    </div>
    <div id="first-content">
        <div id="center-box-wrapper">
            <div id="center-box">
                <div id="center-logo">
                    <a href="">
                        <img src="{% static 'img/logo.png' %}" alt="磁力搜索"></a>
                </div>
                <div id="search-box">
                    <form id="search-form" action="{% url 'app:search' %}" enctype="multipart/form-data" method="get" role="form">
                        <input type="text" id="search" name="q" autocomplete="off" placeholder="搜搜你懂的">
                        <input type="submit" id="btnSearch" value="搜 索" class="blue"></form>
                    <div class="info-box">
                        <ul>
                            <li>
                                <a href="{% url 'app:search' %}?q=喜剧之王">喜剧之王</a></li>
                            <li>
                            <li>
                                <a href="{% url 'app:search' %}?q=泰坦尼克号">泰坦尼克号</a></li>
                            <li>
                            <li>
                                <a href="{% url 'app:search' %}?q=肖申克的救赎">肖申克的救赎</a></li>
                            <li>
                            <li>
                                <a href="{% url 'app:search' %}?q=一路向西">一路向西</a></li>
                            <li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="push"></div>
</div>
{% endblock content %}

ex06javdb8Com/bt-master/templates/app/search.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<div id="wrapper">
    <div class="top-bar">
        <span class="first"><a href="/">首页</a></span><span class="top_fav">
        <a href="{% url 'app:commit' %}" target="_blank">提交链接</a></span>
    </div>
    <div class="header-div">
        <form class="search-form"   action="{% url 'app:search' %}" enctype="multipart/form-data" method="get" role="form">
            <a href="/" title="磁力搜索" class="fl">
                <img src="{% static 'img/logo.png' %}" alt="磁力搜索" class="nav-logo"></a>
            <input type="text" id="search" title="Search" value="{{q}}"
                   autocomplete="off" name="q" placeholder="搜搜你懂的" class="fl mt25">
            <input style="line-height:32px;" type="submit" id="btnSearch" value="搜 索" class=" blue fl mt25">
        </form>
    </div>
    <div id="sort-bar">
        <a href="" rel="nofollow">时间</a>
        <a href="" rel="nofollow">热度</a>
        <a href="" rel="nofollow">大小</a>
    </div>
    <div id="content">
        <div id="wall">
            <div class="search-statu">
                <span>大约{{record_count}}条结果，耗时 {{duration}} 秒。</span><span></span>
            </div>
            <div class="row">
                <div class="search-list col-md-8">

                    {% for item in link_list %}
                     <div class="search-item">
                        <div class="item-title">
                            <h3>
                                <a href="{% url 'app:detail' item.pk %}" >
                                    {{item.title}}
                                </a>
                            </h3>
                        </div>
                        <div class="item-list">
                            {{item.desc}}
                        </div>
                        <div class="item-bar">
                            <span class="cpill fileType1">视频</span>
                            <span>创建时间： <b>{{item.timestamp}}</b></span>
                            <span><b class="cpill yellow-pill">{{item.size}}</b></span>
                            <span>视频热度：<b>{{item.hot}}</b></span>
                        </div>
                    </div>
                    {% empty %}
                    <h3>暂无搜索结果</h3>
                    {% endfor %}


                    {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="nextpage"><a href="?page={{ page_obj.previous_page_number }}{% if q %}&q={{q}}{% endif %}">«</a>
                            </li>
                            {% endif %}
                            {% for i in page_list %}
                            {% if page_obj.number == i %}
                            <li class="active"><a href="?page={{ i }}{% if q %}&q={{q}}{% endif %}">{{ i }}</a></li>
                            {% else %}
                            <li class=""><a href="?page={{ i }}{% if q %}&q={{q}}{% endif %}">{{ i }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="nextpage"><a
                                href="?page={{ page_obj.next_page_number }}{% if q %}&q={{q}}{% endif %}">»</a>
                            </li>
                            {% endif %}
                        </ul>
                    {% endif %}

                    <div style="height:50px;"></div>

                </div>
                <div class="search-tips col-md-2">
                    <div class="search-notice">
                        本站主要用于演示软件项目，不以盈利为目的. 本站没有储存任何数据，亦不对结果承担任何责任！本站已经屏蔽了99%的非法链接，如发现非法，侵权的内容请在线举报，谢谢合作！<br>客服邮箱：net936@163.com
                    </div>
                    <div id="latest-search">
                        <span class="latest-desc">大家都在搜：</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ex06javdb8Com/bt-master/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>种子磁力搜索网站</title>
    <meta name="keywords" content="磁力链接,磁力搜索,磁力链,bt搜索,种子搜索">
    <meta name="description" content="基于python开发的专业强大的磁力链接搜索引擎,这里有超过千万的磁力链提供搜索">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="applicable-device" content="pc,mobile">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style_v2.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/layer.css' %}" id="layuicss-layer">
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?409f08d2486b73b1991beac068018857";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
    </script>


</head>

<body>

{% block content %}
{% endblock content %}

{% include "base/footer.html" %}

<script src="{% static 'js/common-v2.js' %}"></script>
<script src="{% static 'js/m-detail.js' %}"></script>
<script src="{% static 'js/clipboard.min.js' %}"></script>

</body>
</html>

ex06javdb8Com/bt-master/templates/base/footer.html
<div class="footer">
      <span>
        <a href="https://mypython.me/about/" rel="nofollow" target="_blank">联系方式</a>|
        <a href="https://github.com/geeeeeeeek/bt" target="_blank">源码地址</a>|
        <a href="/">磁力搜索</a>|
        <a href="/">种子搜索</a>
      </span>
</div>

ex06javdb8Com/bt-master/templates/base/form_errors.html
{% if form.errors %}
<div class="ui info message">
    <ul class="list">

        {% for field in form %}
        {% for error in field.errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li class="item">{{ error|escape }}</li>
        {% endfor %}
    </ul>
</div>

{% endif %}

ex06javdb8Com/bt-master/templates/base/form_messages.html
{% if messages %}
<div class="ui info message">
    {% for message in messages %}
    <div class="item">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}